baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site 3'
theme = 'ananke'

[menu]
  [[menu.main]]
    name ='about'
    url = '/about/'

[params]
featured_image_class="cover bg-center"
cover_dimming_class = "bg-black-70"
# hide_home_featured_image = true
  # show_all_posts_button=true
#   mainSections=["post"]
# featured_image = "/images/a.jpg"
# # description = "The last theme you'll ever need. Maybe."
# # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
# background_color_class = "bg-black"
# # background_color_class = "bg-green"
# # background_color_class = "bg-yellow"
# # recent_posts_number = 3

